// <auto-generated />
namespace RPG.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class t0202_1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(t0202_1));
        
        string IMigrationMetadata.Id
        {
            get { return "201702021551191_t0202_1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
