// <auto-generated />
namespace RPG.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tet));
        
        string IMigrationMetadata.Id
        {
            get { return "201702051223358_tet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
